### ISSUE TITLE
Executing tests in series

### ISSUE THREAD

**Issue by dainbrump** [aarontrank/gulp-jest#45]
Perhaps I'm missing something, but it seems that gulp-jest is running the complete suite of tests in parallel. The result being that some of my tests require setups and teardowns that seems to create port / IP usage conflicts. Is there a way to force the plugin to run the tests in series? If I'm interpreting the behavior incorrectly, please let me know.

**Comment by aarontrank** [comment]
not sure if this is still relevant.  If it is, feel free to reopen
