### ISSUE TITLE
Gulp Coverage is unknown.

### ISSUE THREAD

**Issue by Rahulgarg30591** [aarontrank/gulp-jest#47]
I am facing the issue with code coverage from Gulp-JEST.

```
gulp.task('jest:cc', () => {
    process.env.NODE_ENV = 'test';
    gulp.src('tests').pipe(jest({
        collectCoverage: true,
        collectCoverageFrom: ['/public/**/*.js,/public/**/*.jsx}'],
        testPathIgnorePatterns: [
            '<rootDir>/dist/', '<rootDir>/build/', '<rootDir>/node_modules/',
            '<rootDir>/docs/', '<rootDir>/tests/', '<rootDir>/gulpTasks/',
        ],
    }));
}).help = 'To run the JEST test cases with code coverage.';
```

If I am missing any configuration please help.

Rest if I change collectCoverageFrom attribute to "**/*.{js,jsx}", test covergae comes for prettify.js and sorter.js of the tests/coverage folder.

@"jest-cli": "^21.2.1", "gulp-jest": "^3.0.1".

**Comment by alansouzati** [comment]
Can you try to provide `rootDir` as part of your config?

https://github.com/grommet/grommet-toolbox/blob/master/src/gulp-tasks-test.js#L87

Another idea is to specify the resolved path or relative path. I think `/public/**/*.js` would resolve to the root dir of your OS. You can try removing the forward slash from your path, like `public/**/*.js`...

let me know

**Comment by Rahulgarg30591** [comment]
`gulp.task('jest:cc', () => {
    process.env.NODE_ENV = 'test';

    return gulp.src('./').pipe(jest({
        collectCoverageFrom: [
            'public/**/*.{js,jsx}',
        ],
        testPathIgnorePatterns: [
            '<rootDir>/dist/', '<rootDir>/build/', '<rootDir>/node_modules/',
            '<rootDir>/docs/', '<rootDir>/gulpTasks/',
        ],
        collectCoverage: true,
        automock: false,
    }));
}).help = 'To run the JEST test cases with code coverage.';`

This is now working, I was working with incorrect gulp start source point. 

Thank You.
