### ISSUE TITLE
Doesn't work in the node environment

### ISSUE THREAD

**Issue by xfg** [aarontrank/gulp-jest#50]
I am trying to use this plugin in node.js environment but get error

```
(node:25310) UnhandledPromiseRejectionWarning: ReferenceError: describe is not defined
    at Object.<anonymous> (/home/user/project/tests/MyFirstTest.spec.js:7:1)
```

gulpfile

```javascript
const gulp = require('gulp');
const jest = require('gulp-jest');

const paths = {
  specs: {
    src: ['tests/MyFirstTest.spec.js']
  }
};

gulp.task('test', () => {
  return gulp.src(paths.specs.src)
    .pipe(jest.default({testEnvironment: 'node'}));
});
```
When I use jest directly then all work as expected. What am I doing wrong?

**Comment by TheDancingCode** [comment]
Did you install the jest-cli locally?

**Comment by xfg** [comment]
Yes, I installed jest-cli locally as the readme recommended.

**Comment by TheDancingCode** [comment]
It seems to work when you pass the directory where your test lives instead of the path of the testfile itself:
```js
const paths = {
  specs: {
    src: ['tests/']
  }
};
```

**Comment by alansouzati** [comment]
does it work if you remove `testEnvironment` ?

**Comment by aarontrank** [comment]
please reopen if issue still persists.
