### ISSUE TITLE
The following tasks did not complete: jest

### ISSUE THREAD

**Issue by jsehn** [aarontrank/gulp-jest#52]
I added a gulp task per the documentation, just runs but it seems the callback is never invoked and I get the following error:

Test Suites: 1 failed, 4 passed, 5 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   0 total
Time:        12.908s
Ran all test suites.
[16:15:08] The following tasks did not complete: jest
[16:15:08] Did you forget to signal async completion?

**Comment by mikeops** [comment]
@jsehn I realize this is an old bug but do you have a `return` statement?

**Comment by aarontrank** [comment]
feel free to reopen if the issue remains
