### ISSUE TITLE
Should only Run Matched Files

### ISSUE THREAD

**Issue by chris-pardy** [aarontrank/gulp-jest#53]
Currently a run of the jest cli is invoked for every file that is matched. While this is *fine* if you have a single top-level test directory if you have multiple test directories than all your tests are run multiple times.

Solution would be to only run the jest cli on the files that are streamed into this gulp plugin. This would mean that gulp.src would be responsible for defining which tests you want to run and this plugin would simply invoke jest.

**Comment by aarontrank** [comment]
feel free to reopen if this issue persists.
