### ISSUE TITLE
TypeError: Cannot read property "runCLI" of undefined (jest v25.1.0)

### ISSUE THREAD

**Issue by chharvey** [aarontrank/gulp-jest#58]
Upgrading **jest-cli** from v24.9.0 to [v25.1.0](https://github.com/facebook/jest/blob/v25.1.0/CHANGELOG.md) causes an error when using with **gulp-jest**.

> TypeError: Cannot read property 'runCLI' of undefined

The stack trace is pasted at the bottom.

I can’t be sure, but I have a feeling that this is caused by one of the breaking changes Jest made, switching from CommonJS exports to ESM exports. That is,

from
```
exports = X;
```
to
```
export default X;
```

<details>
<summary>Stack Trace: <strong>TypeError: Cannot read property 'runCLI' of undefined</strong></summary>
<pre>
at DestroyableTransform._transform (/Users/chharvey/…/node_modules/gulp-jest/lib/index.js:29:23)
at DestroyableTransform.Transform._read (/Users/chharvey/…/node_modules/readable-stream/lib/_stream_transform.js:184:10)
at DestroyableTransform.Transform._write (/Users/chharvey/…/node_modules/readable-stream/lib/_stream_transform.js:172:83)
at doWrite (/Users/chharvey/…/node_modules/readable-stream/lib/_stream_writable.js:428:64)
at writeOrBuffer (/Users/chharvey/…/node_modules/readable-stream/lib/_stream_writable.js:417:5)
at DestroyableTransform.Writable.write (/Users/chharvey/…/node_modules/readable-stream/lib/_stream_writable.js:334:11)
at DestroyableTransform.ondata (/Users/chharvey/…/node_modules/readable-stream/lib/_stream_readable.js:619:20)
at DestroyableTransform.emit (events.js:223:5)
at DestroyableTransform.EventEmitter.emit (domain.js:498:23)
at addChunk (/Users/chharvey/…/node_modules/readable-stream/lib/_stream_readable.js:291:12)
</pre>
</details>

**Comment by mick352** [comment]
This blocked the upgrade of https://github.com/postcss/postcss-scss for me, which is reported as a security vulnerability due to minimist:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ stylelint                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ stylelint > postcss-sass > gonzales-pe > minimist            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1179                        │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by tet-lenovo** [comment]
Any chance a fix for this will be released soon?  We would like to update Jest but are stuck because of this issue.

**Comment by thinkh** [comment]
Same here. The PR #59 is already filed. Can somebody please merge it and publish the new version on npm?

**Comment by aarontrank** [comment]
I've merged your PR. Thanks!  I'll reach out to the owner on npm (it's not me) to publish the new version

**Comment by Mikrovolnovka** [comment]
@aarontrank don't you know when it's going to happen?

**Comment by aarontrank** [comment]
I recently inherited this package on github but don't have ownership or
admin access on npm.  I've tried reaching out to the npm owner, but he is
unresponsive so far.  If you want to reach out to him too, maybe we can
mount enough pressure for him to take action.

**Comment by Mikrovolnovka** [comment]
@alansouzati could you please release the new version of this package to npm please?

**Comment by mick352** [comment]
> If you want to reach out to him too, maybe we can
mount enough pressure for him to take action.

@aarontrank : I tried in vain to find the owner of the npm repo . If you shared a way to get in touch with him, it might make it easier to mount the pressure.

**Comment by Mikrovolnovka** [comment]
@aarontrank on the npm lib link to repo seems like this:
<img width="306" alt="Screen Shot 2020-04-29 at 11 14 00" src="https://user-images.githubusercontent.com/1439238/80574476-9312a480-8a0a-11ea-89f6-a4db0da0c7e4.png">
But if you click it, it leads to this repo.
Seems there is redirection on that repo.

**Comment by alansouzati** [comment]
Please give me an npm user and I will grant access to maintain the repo. I’m on parental leave and also I’m not doing much open source stuff anymore

**Comment by mick352** [comment]
Thanks ! While it seems best if @aarontrank offers his npm user, you can use https://www.npmjs.com/~mick_heise if he does not respond until you next see this @alansouzati . He could then get access from me, so it's off your shoulders. Congratulations on the birth of your child !

**Comment by aarontrank** [comment]
@mick352 would you like to take over this package?  If so I can transfer it to you

**Comment by aarontrank** [comment]
> Please give me an npm user and I will grant access to maintain the repo. I’m on parental leave and also I’m not doing much open source stuff anymore
> […](#)
> Sent from my iPhone
> On Apr 29, 2020, at 1:15 AM, Dmytro Yaroshenko ***@***.***> wrote: ﻿ @aarontrank on the npm lib link to repo seems like this: But if you click it, it leads to this repo. Seems there is redirection on that repo. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I'm at https://www.npmjs.com/~aarontrank

**Comment by mick352** [comment]
@aarontrank : it's fine where it is, if that's alright with you. Thanks

**Comment by Mikrovolnovka** [comment]
@aarontrank @alansouzati any update on this?

**Comment by mick352** [comment]
@Mikrovolnovka : @alansouzati can also be contacted via LinkedIn (linked via stackoverflow) https://www.linkedin.com/in/alansouzati

**Comment by Mikrovolnovka** [comment]
@mick352 I don't want to bother too much. :)

**Comment by mick352** [comment]
He's on parental leave and does not read anything else, it seems. His last message to this Issue was correlated to me contacting him on LinkedIn. Do as you like.
